// Put icons, thumbnails and screenshots in public/projects/<slug>/ and reference them as "/projects/<slug>/file.png".
export const projects = [
  {
    year: "2026",
    name: "Reelferry",
    category: "Product",
    url: "https://reelferry.tcmhack.com",
    icon: "/projects/reelferry/icon.png",
    thumbnail: "/projects/reelferry/thumbnail.png",
    description:
      "Send public Instagram Reels to your YouTube channels as Shorts, one at a time or a whole batch, from a browser side panel.",
    tags: ["Web App", "Browser Extension", "Instagram", "YouTube Shorts"],
    screenshots: [
      "/projects/reelferry/screenshots/shot-1.png",
      "/projects/reelferry/screenshots/shot-2.png",
      "/projects/reelferry/screenshots/shot-3.png",
      "/projects/reelferry/screenshots/shot-4.png",
      "/projects/reelferry/screenshots/shot-5.png",
    ],
  },
  {
    year: "2021-2026",
    category: "Product",
    name: "Social Media Downloader",
    url: "https://socialdownloader.in",
    icon: "/projects/socialdownloader/icon.png",
    thumbnail: "/projects/socialdownloader/thumbnail-440x280.png",
    description:
      "Download photos, videos and reels from Instagram, Facebook and X in one click — no link pasting needed.",
    tags: ["Web App", "Browser Extension", "Social Media Video downloader"],
    screenshots: [],
  },
  {
    name: "TCMHACK",
    year: "2018-2026",
    url: "https://www.tcmhack.com",
    icon: "/projects/tcmhack/logo.png",
    description:
      "We provide software development services, innovative products, and web development tutorials to help you build apps faster and better.",
    thumbnail: "",
    screenshots: [],
    category: "Product",
    tags: ["Web Development", "Blog"],
  },
  {
    name: "UserAdvocate",
    icon: "",
    url: "https://www.uxarmy.com",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "UXArmy",
    year: "2017",
    tags: ["Browser Extension", "React"],
  },
  {
    name: "UXToolkit",
    icon: "",
    url: "https://www.uxarmy.com",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "UXArmy",
    year: "2019",
    tags: ["React", "Ant Design"],
  },
  {
    name: "TempSMS",
    icon: "",
    url: "https://tempsms.tcmhack.com",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Open source",
    year: "2025",
    tags: ["JavaScript", "Web App"],
  },
  {
    name: "Bookmarks Management",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/bookmarks-management/djdlkoihbhgbjfabpgpclknhjoalmkjk",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2020",
    tags: ["Browser Extension", "React", "Ant Design", "Chrome APIs"],
  },
  {
    name: "Pic Portal",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/ddknoicjjimjmfkhhggdcfnaadnjakko",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2020",
    tags: ["Browser Extension", "React", "Tailwind CSS", "Pexels API"],
  },
  {
    name: "HackerEarth Challenges",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/hackerearth-challenges/infidkkgnkakeecjakbpeejpdknncpdk",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2020",
    tags: ["Browser Extension", "React", "TypeScript", "Tailwind CSS"],
  },
  {
    name: "Currency Converter",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/currency-converter/djijpkidiloakhgopmijjdcancpfekma",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2018",
    tags: ["Browser Extension", "JavaScript", "Chrome APIs"],
  },
  {
    name: "YouTube to S3",
    icon: "",
    url: "https://github.com/tikamchand06/youtube2s3",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Open source",
    year: "2022",
    tags: ["Node.js", "AWS S3"],
  },
  {
    name: "Character Counter",
    icon: "",
    url: "https://github.com/tikamchand06/character-counter",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Open source",
    year: "2024",
    tags: ["JavaScript"],
  },
  {
    name: "Jira Banner Remover",
    icon: "",
    url: "https://github.com/tikamchand06/Jira-Deactivation-Banner-Remover",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Browser extension",
    year: "2024",
    tags: ["Browser Extension", "JavaScript", "Chrome APIs"],
  },
  {
    name: "YouTube Clone",
    icon: "",
    url: "https://github.com/tikamchand06/youtube-clone",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Open source",
    year: "2019",
    tags: ["React", "Ant Design", "Firebase"],
  },
]
