export const projects = [
  {
    year: "2026",
    name: "Reelferry",
    category: "Product",
    url: "https://reelferry.tcmhack.com",
    icon: "/projects/reelferry/icon.png",
    thumbnail: "/projects/reelferry/thumbnail.png",
    description:
      "Send public Instagram Reels to your YouTube channels as Shorts, one at a time or a whole batch, from a browser side panel.",
    tags: ["Web App", "Instagram", "YouTube Shorts"],
    browsers: ["chrome", "firefox"],
  },
  {
    year: "2021",
    category: "Product",
    name: "Social Media Downloader",
    url: "https://socialdownloader.in",
    icon: "/projects/social-media-downloader/icon.png",
    thumbnail: "/projects/social-media-downloader/thumbnail.png",
    description:
      "Download photos, videos and reels from Instagram, Facebook and X in one click — no link pasting needed.",
    tags: ["Web App", "Instagram", "Facebook", "X (Twitter)"],
    browsers: ["chrome", "firefox"],
  },
  {
    year: "2018",
    name: "TCMHACK",
    url: "https://www.tcmhack.com",
    icon: "/projects/tcmhack/icon.png",
    description:
      "A developer hub offering software development services, in-house products, and practical web development tutorials on JavaScript, React and more.",
    thumbnail: "/projects/tcmhack/thumbnail.png",
    category: "Product",
    tags: ["Website", "Blog", "Web Development"],
  },
  {
    year: "2017",
    name: "UserAdvocate",
    url: "https://www.uxarmy.com",
    icon: "/projects/useradvocate/icon.png",
    description:
      "Use the UserAdvocate extension to participate in user studies you received via UXArmy.",
    thumbnail: "/projects/useradvocate/thumbnail.png",
    category: "Browser Extension",
    tags: ["React", "Vite", "Ant Design", "Chrome APIs"],
    browsers: ["chrome"],
  },
  {
    year: "2020",
    name: "Bookmarks Management",
    icon: "/projects/bookmarks-management/icon.png",
    thumbnail: "/projects/bookmarks-management/thumbnail.png",
    url: "https://github.com/tikamchand06/bookmarks-management",
    description:
      "A straightforward tool for organizing your entire bookmark collection.",
    category: "Browser Extension",
    tags: ["React", "Ant Design", "Chrome APIs"],
    browsers: ["chrome"],
  },
  {
    year: "2018",
    name: "Currency Converter",
    icon: "/projects/currency-converter/icon.png",
    url: "https://github.com/tikamchand06/currency-converter",
    description:
      "Instantly convert currencies with real-time exchange rates. Perfect for shopping, travel, or financial tracking in your browser.",
    thumbnail: "/projects/currency-converter/thumbnail.png",
    category: "Browser Extension",
    tags: ["React", "Vite", "Ant Design", "Chrome APIs"],
    browsers: ["chrome"],
  },
  {
    year: "2024",
    name: "Character Counter",
    icon: "/projects/character-counter/icon.png",
    thumbnail: "/projects/character-counter/thumbnail.png",
    url: "https://github.com/tikamchand06/character-counter",
    description:
      "Calculate the number of letters, words, sentences, paragraphs, and spaces in a piece of text.",
    category: "Browser Extension",
    browsers: ["chrome"],
    tags: ["JavaScript", "Chrome APIs"],
  },
  {
    year: "2020",
    name: "HackerEarth Challenges",
    icon: "/projects/hackerearth-challenges/icon.png",
    thumbnail: "/projects/hackerearth-challenges/thumbnail.png",
    url: "https://github.com/tikamchand06/hackerearth-challanges",
    description:
      "HackerEarth Extension keeps you updated with upcoming challenges and other resources on HackerEarth.",
    category: "Browser Extension",
    tags: ["React", "Vite", "Tailwind CSS"],
    browsers: ["chrome"],
  },
  {
    year: "2020",
    name: "Pic Portal",
    icon: "/projects/pic-portal/icon.png",
    thumbnail: "/projects/pic-portal/thumbnail.png",
    url: "https://github.com/tikamchand06/pic-portal",
    description:
      "Your gateway to a world of images. Streamline your search and download high-quality pictures effortlessly.",
    category: "Browser Extension",
    tags: ["React", "Ant Design", "Pexels API"],
    browsers: ["chrome"],
  },
  {
    year: "2023",
    name: "Full-Page Screenshot 2.0",
    icon: "/projects/full-page-screenshot/icon.png",
    url: "https://chromewebstore.google.com/detail/full-page-screenshot-20/leeampediajiofkmbbodpogaaimcncne?hl=en",
    description:
      "Automatically takes screenshot of the entire page within seconds!",
    thumbnail: "",
    category: "Browser Extension",
    tags: ["React", "Webpack", "Ant Design", "Chrome APIs"],
    browsers: ["chrome"],
    client: "Sal Eriotes",
    clientUrl: "",
  },
  {
    year: "2022",
    name: "Undo Closed Tabs 2.0",
    icon: "/projects/undo-closed-tabs/icon.png",
    url: "https://chromewebstore.google.com/detail/cfcfmcnjnfhnimdbiodmalbdehbppbeo",
    description: "Re-open all the closed tabs 🗂️ with one click.",
    thumbnail: "",
    category: "Browser Extension",
    tags: ["JavaScript", "Chrome APIs"],
    browsers: ["chrome"],
    client: "Sal Eriotes",
    clientUrl: "",
  },
  {
    year: "2023",
    name: "Newsfeed Eradicator 2.0",
    icon: "/projects/newsfeed-eradicator/icon.png",
    url: "https://chromewebstore.google.com/detail/clfonknljamomadgkcciofnhfegjinhd",
    description:
      "Removes the entire newsfeed and replaces it with an inspiring quote to block out all the negativity",
    thumbnail: "",
    browsers: ["chrome"],
    category: "Browser Extension",
    tags: ["React", "Ant Design", "Chrome APIs"],
    client: "Sal Eriotes",
    clientUrl: "",
  },
  {
    year: "2022",
    name: "Dark Mode 2.0",
    icon: "/projects/dark-mode/icon.png",
    url: "https://chromewebstore.google.com/detail/falojlkngkajkbnfoolnagafeeilogjo",
    description:
      "Allows you to turn on dark mode for any website & enables night shift that changes the tint to help avoid strain on your eyes!",
    thumbnail: "",
    browsers: ["chrome"],
    category: "Browser Extension",
    tags: ["JavaScript", "Chrome APIs"],
    client: "Sal Eriotes",
    clientUrl: "",
  },
  {
    year: "2022",
    name: "Color Eye Dropper 2.0",
    icon: "/projects/color-eye-dropper/icon.png",
    url: "https://chromewebstore.google.com/detail/cmboomkdkngiglblihhlokadkkocjjaa",
    description:
      "Allows you to pick color from any web page or from our advanced color picker!",
    thumbnail: "",
    browsers: ["chrome"],
    category: "Browser Extension",
    tags: ["JavaScript", "Chrome APIs"],
    client: "Sal Eriotes",
    clientUrl: "",
  },
]
