// browsers: any of "chrome", "firefox", "opera", "brave".
// Put icons, thumbnails and screenshots in public/projects/<slug>/ and reference them as "/projects/<slug>/file.png".
export const projects = [
  {
    year: "2026",
    name: "Reelferry",
    category: "Product",
    url: "https://reelferry.tcmhack.com",
    icon: "/projects/reelferry/icon.png",
    thumbnail: "/projects/reelferry/thumbnail.png",
    description:
      "Send public Instagram Reels to your YouTube channels as Shorts, one at a time or a whole batch, from a browser side panel.",
    tags: ["Web App", "Browser Extension", "Instagram", "YouTube Shorts"],
    browsers: ["chrome"],
    screenshots: [
      "/projects/reelferry/screenshots/shot-1.png",
      "/projects/reelferry/screenshots/shot-2.png",
      "/projects/reelferry/screenshots/shot-3.png",
      "/projects/reelferry/screenshots/shot-4.png",
      "/projects/reelferry/screenshots/shot-5.png",
    ],
  },
  {
    year: "2021-CURRENT",
    category: "Product",
    name: "Social Media Downloader",
    url: "https://socialdownloader.in",
    icon: "/projects/socialdownloader/icon.png",
    thumbnail: "/projects/socialdownloader/thumbnail-440x280.png",
    description:
      "Download photos, videos and reels from Instagram, Facebook and X in one click — no link pasting needed.",
    tags: ["Web App", "Browser Extension", "Social Media Video downloader"],
    browsers: ["chrome"],
    screenshots: [],
  },
  {
    name: "TCMHACK",
    year: "2018-CURRENT",
    url: "https://www.tcmhack.com",
    icon: "/projects/tcmhack/logo.png",
    description:
      "We provide software development services, innovative products, and web development tutorials to help you build apps faster and better.",
    thumbnail: "",
    screenshots: [],
    category: "Product",
    tags: ["Web Development", "Blog"],
  },
  {
    name: "UserAdvocate",
    url: "https://www.uxarmy.com",
    icon: "/projects/useradvocate/icon.png",
    description:
      "Use the UserAdvocate extension to participate in user studies you received via UXArmy.",
    thumbnail: "",
    screenshots: [],
    category: "UXArmy",
    year: "2017-CURRENT",
    tags: ["Browser Extension", "React"],
    browsers: ["chrome"],
  },
  {
    year: "2023",
    name: "Full-Page Screenshot 2.0",
    icon: "/projects/fullpage-screenshot/icon_128.png",
    url: "https://chromewebstore.google.com/detail/full-page-screenshot-20/leeampediajiofkmbbodpogaaimcncne?hl=en",
    description:
      "Automatically takes screenshot of the entire page within seconds!",
    thumbnail: "",
    screenshots: [],
    category: "Chrome Extension",
    tags: [
      "React",
      "Webpack",
      "Ant Design",
      "Chrome APIs",
      "Browser Extension",
    ],
    browsers: ["chrome"],
  },
  {
    name: "Bookmarks Management",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/bookmarks-management/djdlkoihbhgbjfabpgpclknhjoalmkjk",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome Extension",
    year: "2020",
    tags: ["Browser Extension", "React", "Ant Design", "Chrome APIs"],
    browsers: ["chrome"],
  },
  {
    name: "Pic Portal",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/ddknoicjjimjmfkhhggdcfnaadnjakko",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2020",
    tags: ["Browser Extension", "React", "Tailwind CSS", "Pexels API"],
    browsers: ["chrome"],
  },
  {
    name: "HackerEarth Challenges",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/hackerearth-challenges/infidkkgnkakeecjakbpeejpdknncpdk",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2020",
    tags: ["Browser Extension", "React", "TypeScript", "Tailwind CSS"],
    browsers: ["chrome"],
  },
  {
    name: "Currency Converter",
    icon: "",
    url: "https://chrome.google.com/webstore/detail/currency-converter/djijpkidiloakhgopmijjdcancpfekma",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    year: "2018",
    tags: ["Browser Extension", "JavaScript", "Chrome APIs"],
    browsers: ["chrome"],
  },
  {
    year: "2022",
    name: "Undo Closed Tabs 2.0",
    icon: "/projects/undoclosedtab/icon128.png",
    url: "https://chromewebstore.google.com/detail/undo-closed-tabs-20/cfcfmcnjnfhnimdbiodmalbdehbppbeo",
    description: "Re-open all the closed tabs 🗂️ with one click.",
    thumbnail: "",
    screenshots: [],
    category: "Chrome extension",
    tags: ["Browser Extension", "JavaScript", "Chrome APIs"],
    browsers: ["chrome"],
  },
  {
    name: "Character Counter",
    icon: "",
    url: "https://github.com/tikamchand06/character-counter",
    description: "",
    thumbnail: "",
    screenshots: [],
    category: "Open source",
    year: "2024",
    tags: ["JavaScript"],
  },
  {
    year: "2023",
    name: "Newsfeed Eradicator 2.0",
    icon: "/projects/newsfeed/icon.png",
    url: "https://chromewebstore.google.com/detail/clfonknljamomadgkcciofnhfegjinhd",
    description:
      "Removes the entire newsfeed and replaces it with an inspiring quote to block out all the negativity",
    thumbnail: "",
    screenshots: [],
    category: "Browser extension",
    tags: ["React", "Ant Design", "Chrome APIs", "Browser Extension"],
  },
  {
    year: "2022",
    name: "Dark Mode 2.0",
    icon: "/projects/darkmode/icon.png",
    url: "https://chromewebstore.google.com/detail/falojlkngkajkbnfoolnagafeeilogjo",
    description:
      "Allows you to turn on dark mode for any website & enables night shift that changes the tint to help avoid strain on your eyes!",
    thumbnail: "",
    screenshots: [],
    category: "Browser extension",
    tags: ["JavaScript", "Chrome APIs", "Browser Extension"],
  },
  {
    year: "2022",
    name: "Color Eye Dropper 2.0",
    icon: "/projects/eye-dropper/icon.png",
    url: "https://chromewebstore.google.com/detail/cmboomkdkngiglblihhlokadkkocjjaa",
    description:
      "Allows you to pick color from any web page or from our advanced color picker!",
    thumbnail: "",
    screenshots: [],
    category: "Browser extension",
    tags: ["JavaScript", "Chrome APIs", "Browser Extension"],
  },
  // {
  //   year: "2022",
  //   name: "Dark Mode 2.0",
  //   icon: "/projects/darkmode/icon.png",
  //   url: "https://chromewebstore.google.com/detail/falojlkngkajkbnfoolnagafeeilogjo",
  //   description:
  //     "Allows you to turn on dark mode for any website & enables night shift that changes the tint to help avoid strain on your eyes!",
  //   thumbnail: "",
  //   screenshots: [],
  //   category: "Browser extension",
  //   tags: ["JavaScript", "Chrome APIs", "Browser Extension"],
  // },
]
